CREATE TABLE Dim_Convenio (
    NR_CONVENIO INT PRIMARY KEY,
    ID_PROPOSTA INT,
    SIT_CONVENIO VARCHAR(100),
    SUBSITUACAO_CONV VARCHAR(100),
    SITUACAO_PUBLICACAO VARCHAR(50),
    INSTRUMENTO_ATIVO VARCHAR(3),
    IND_OPERA_OBTV VARCHAR(3),
    NR_PROCESSO VARCHAR(20),
    UG_EMITENTE VARCHAR(20)
);

CREATE TABLE Dim_Tempo (
    Data DATE PRIMARY KEY,
    DIA INT,
    MES INT,
    ANO INT,
    DIA_ASSIN_CONV DATE,
    DIA_PUBL_CONV DATE,
    DIA_INIC_VIGENC_CONV DATE,
    DIA_FIM_VIGENC_CONV DATE,
    DIA_FIM_VIGENC_ORIGINAL_CONV DATE
);

CREATE TABLE Dim_Situacao (
    NR_CONVENIO INT PRIMARY KEY,
    DIAS_PREST_CONTAS INT,
    DIA_LIMITE_PREST_CONTAS DATE,
    DATA_SUSPENSIVA DATE,
    DATA_RETIRADA_SUSPENSIVA DATE,
    DIAS_CLAUSULA_SUSPENSIVA INT,
    SITUACAO_CONTRATACAO VARCHAR(100),
    IND_ASSINADO VARCHAR(3),
    MOTIVO_SUSPENSAO VARCHAR(255)
);

CREATE TABLE Fato_Financeiro (
    NR_CONVENIO INT,
    VL_GLOBAL_CONV DECIMAL(18,2),
    VL_REPASSE_CONV DECIMAL(18,2),
    VL_CONTRAPARTIDA_CONV DECIMAL(18,2),
    VL_EMPENHADO_CONV DECIMAL(18,2),
    VL_DESEMBOLSADO_CONV DECIMAL(18,2),
    VL_SALDO_REMAN_TESOURO DECIMAL(18,2),
    VL_SALDO_REMAN_CONVENENTE DECIMAL(18,2),
    VL_RENDIMENTO_APLICACAO DECIMAL(18,2),
    VL_INGRESSO_CONTRAPARTIDA DECIMAL(18,2),
    VL_SALDO_CONTA DECIMAL(18,2),
    VALOR_GLOBAL_ORIGINAL_CONV DECIMAL(18,2),
    PRIMARY KEY (NR_CONVENIO),
    FOREIGN KEY (NR_CONVENIO) REFERENCES Dim_Convenio(NR_CONVENIO),
    FOREIGN KEY (NR_CONVENIO) REFERENCES Dim_Situacao(NR_CONVENIO)
);

CREATE TABLE Fato_Tempo (
    NR_CONVENIO INT,
    Data DATE,
    FOREIGN KEY (NR_CONVENIO) REFERENCES Dim_Convenio(NR_CONVENIO),
    FOREIGN KEY (Data) REFERENCES Dim_Tempo(Data),
    PRIMARY KEY (NR_CONVENIO, Data)
);
